server:
  port: 8082
spring:
  application:
    name: lagou-service-email
  mail:
    host: smtp.qq.com
    username: username
    password: password
    properties.mail.smtp.ssl.enable: true
  # nacos配置
  cloud:
    nacos:
      discovery:
        # 集群中各节点信息都配置在这里（域名-VIP-绑定映射到各个实例的地址信息）
        server-addr: 192.168.33.10:8848
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.lagou.edu.service.impl
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
    host: 127.0.0.1
  registry:
    # 挂载到 Spring Cloud 的注册中心
    address: spring-cloud://localhost