server:
  port: 8081

spring:
  application:
    name: lagou-service-code
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.33.10:3306/spring_cloud?serverTimezone=CST&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #避免将驼峰命名转换为下划线命名
  # nacos配置
  cloud:
    nacos:
      discovery:
        # 集群中各节点信息都配置在这里（域名-VIP-绑定映射到各个实例的地址信息）
        server-addr: 192.168.33.10:8848
  main:
    allow-bean-definition-overriding: true

#针对的被调⽤⽅微服务名称,不加就是全局⽣效
lagou-service-email:
  ribbon:
    #请求连接超时时间
    ConnectTimeout: 20000
    #请求处理超时时间
    ##########################################Feign超时时长设置
    ReadTimeout: 20000
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #负载策略调整

management:
  endpoints:
    web:
      exposure:
        include: "*"
dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.lagou.edu.service.impl
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
    host: 127.0.0.1
  registry:
    # 挂载到 Spring Cloud 的注册中心
    address: spring-cloud://localhost
  cloud:
    subscribed-services: lagou-service-email